### ISSUE TITLE
DSI

### ISSUE THREAD

**Issue by xiehao-ai** [ShuyueG/CVI_using_DSI#1]
Thanks for you code.
May I ask if the code of DSI can be used to complete the paper '' Data Separability for Neural Network Classifiers and the Development of a Separability Index''

**Comment by ShuyueG** [comment]
> Thanks for you code.
> May I ask if the code of DSI can be used to complete the paper '' Data Separability for Neural Network Classifiers and the Development of a Separability Index''

Yes! It's exact the right code to compute the DSI in that paper. 
Thanks for your interest! Please feel free to ask me if you have any questions.

**Comment by xiehao-ai** [comment]
Thank you very much for your reply! 
I have recently read your paper “Data Separability for Neural Network Classifiers and the Development of a Separability Index”. I am very interested in this article and have studied it carefully. The K-S test is often used to compare whether two sample sets have the same distribution, and its input is original data. I would like to know the reason for choosing ICD and BCD as the input of DSI.

**Comment by xiehao-ai** [comment]
I have written the following code for DSI method under the two-class situation as described in your paper.


def DSI(source1, source2):  

    dist_1 = dists(source1)  
    dist_2 = dists(source2) 
    distbtw = dist_btw(source1, source2)  

    D_Sep_1, _ = ks_2samp(dist_1, distbtw)
    D_Sep_2, _ = ks_2samp(dist_2, distbtw)

    return (D_Sep_1 + D_Sep_2) / 2


But I got some trouble when I try to implement experiments under n-class situation. If possible, could you please provide the source program about the experiments on CIFAR-10/100 datasets. 
Thank you very much for your kind consideration!

**Comment by ShuyueG** [comment]
> Thank you very much for your reply!
> I have recently read your paper “Data Separability for Neural Network Classifiers and the Development of a Separability Index”. I am very interested in this article and have studied it carefully. The K-S test is often used to compare whether two sample sets have the same distribution, and its input is original data. I would like to know the reason for choosing ICD and BCD as the input of DSI.

It's a good question. The reason to use ICD and BCD instead of the original data to compute the K-S test is that the original data may be in a very high dimension. All values in ICD and BCD sets are 1-D (Euclidean) distances. Thus, **it transforms a n-D K-S test to a 1-D K-S test problem**. And, our Theorem has proved that **if and only if the two original sample sets have the same distribution, the ICD and BCD sets have the same distribution**.

**Comment by ShuyueG** [comment]
> I have written the following code for DSI method under the two-class situation as described in your paper.
> 
> def DSI(source1, source2):
> 
> ```
> dist_1 = dists(source1)  
> dist_2 = dists(source2) 
> distbtw = dist_btw(source1, source2)  
> 
> D_Sep_1, _ = ks_2samp(dist_1, distbtw)
> D_Sep_2, _ = ks_2samp(dist_2, distbtw)
> 
> return (D_Sep_1 + D_Sep_2) / 2
> ```
> 
> But I got some trouble when I try to implement experiments under n-class situation. If possible, could you please provide the source program about the experiments on CIFAR-10/100 datasets.
> Thank you very much for your kind consideration!

The DSI code in this project is for n-class situation. It is exactly the same code we used on CIFAR-10/100 datasets. The code is copied below:

```
def separability_index_ks_2samp(X, labels):  # KS test on ICD and BCD
    classes = np.unique(labels)
    SUM = 0
    for c in classes:
        pos = X[np.squeeze(labels == c)]
        neg = X[np.squeeze(labels != c)]
        dist_pos = dists(pos)
        distbtw = dist_btw(pos, neg)
        D, _ = ks_2samp(dist_pos, distbtw)  # KS test
        SUM += D
    SUM = SUM / classes.shape[0]  # normed: b/c ks_2samp ranges [0,1]
    return SUM
```

**Comment by xiehao-ai** [comment]
hi,
I am confused about the  theorem 3.1 in paper ''Data Separability for Neural Network Classifiers and the Development of a Separability Index ''. This theorem proves that if and only if the two original sample sets have the same distribution, the ICD and BCD sets have the same distribution. 
Although the ICD and BCD sets have the same distribution, how to determine whether the distribution of ICD and BCD can represent the distribution of X and Y.
If X and Y have different distribution, such as source domain and target domain in domain adaptation task, we want to measure the discrepancy of source samples and target samples, whether the theorem 3.1 can be used?

**Comment by ShuyueG** [comment]
> hi,
> I am confused about the theorem 3.1 in paper ''Data Separability for Neural Network Classifiers and the Development of a Separability Index ''. This theorem proves that if and only if the two original sample sets have the same distribution, the ICD and BCD sets have the same distribution.
> Although the ICD and BCD sets have the same distribution, how to determine whether the distribution of ICD and BCD can represent the distribution of X and Y.
> If X and Y have different distribution, such as source domain and target domain in domain adaptation task, we want to measure the discrepancy of source samples and target samples, whether the theorem 3.1 can be used?

I think DSI can be used to measure the discrepancy of two sample sets. That DSI of X and Y sets is close to zero means X and Y sets have the same distribution. That is, their discrepancy does not exist.

**Comment by xiehao-ai** [comment]
> 
> 
> > hi,
> > I am confused about the theorem 3.1 in paper ''Data Separability for Neural Network Classifiers and the Development of a Separability Index ''. This theorem proves that if and only if the two original sample sets have the same distribution, the ICD and BCD sets have the same distribution.
> > Although the ICD and BCD sets have the same distribution, how to determine whether the distribution of ICD and BCD can represent the distribution of X and Y.
> > If X and Y have different distribution, such as source domain and target domain in domain adaptation task, we want to measure the discrepancy of source samples and target samples, whether the theorem 3.1 can be used?
> 
> I think DSI can be used to measure the discrepancy of two sample sets. That DSI of X and Y sets is close to zero means X and Y sets have the same distribution. That is, their discrepancy does not exist.

Thank you very much for your reply! And, I would like to know if the ICD and BCD can represent the distribution of X and Y.

**Comment by ShuyueG** [comment]
> > > hi,
> > > I am confused about the theorem 3.1 in paper ''Data Separability for Neural Network Classifiers and the Development of a Separability Index ''. This theorem proves that if and only if the two original sample sets have the same distribution, the ICD and BCD sets have the same distribution.
> > > Although the ICD and BCD sets have the same distribution, how to determine whether the distribution of ICD and BCD can represent the distribution of X and Y.
> > > If X and Y have different distribution, such as source domain and target domain in domain adaptation task, we want to measure the discrepancy of source samples and target samples, whether the theorem 3.1 can be used?
> > 
> > 
> > I think DSI can be used to measure the discrepancy of two sample sets. That DSI of X and Y sets is close to zero means X and Y sets have the same distribution. That is, their discrepancy does not exist.
> 
> Thank you very much for your reply! And, I would like to know if the ICD and BCD can represent the distribution of X and Y.

No, ICD and BCD sets cannot represent the distributions of X and Y because ICD and BCD sets are in 1-D, they have lost a lot of information of the distributions of X and Y. They can ONLY use to show the similarity between the distributions of X and Y by the Theorem.

**Comment by xiehao-ai** [comment]
> 
> 
> > > > hi,
> > > > I am confused about the theorem 3.1 in paper ''Data Separability for Neural Network Classifiers and the Development of a Separability Index ''. This theorem proves that if and only if the two original sample sets have the same distribution, the ICD and BCD sets have the same distribution.
> > > > Although the ICD and BCD sets have the same distribution, how to determine whether the distribution of ICD and BCD can represent the distribution of X and Y.
> > > > If X and Y have different distribution, such as source domain and target domain in domain adaptation task, we want to measure the discrepancy of source samples and target samples, whether the theorem 3.1 can be used?
> > > 
> > > 
> > > I think DSI can be used to measure the discrepancy of two sample sets. That DSI of X and Y sets is close to zero means X and Y sets have the same distribution. That is, their discrepancy does not exist.
> > 
> > 
> > Thank you very much for your reply! And, I would like to know if the ICD and BCD can represent the distribution of X and Y.
> 
> No, ICD and BCD sets cannot represent the distributions of X and Y because ICD and BCD sets are in 1-D, they have lost a lot of information of the distributions of X and Y. They can ONLY use to show the similarity between the distributions of X and Y by the Theorem.

OK! Thank you very much!
